# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://projectglow.org
title: Glow
email: proj-glow@googlegroups.com
author: Glow
description: > # "Write an awesome description for your new site here. 
  Project Glow is genomics on Apache Spark made simple.
copyright: 'Copyright &copy; 2019 Project Glow. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: code
    url: https://github.com/projectglow/glow
  - icon: book
    title: docs
    url: https://readthedocs.org
  - icon: envelope
    title: forum
    url: https://groups.google.com/forum/#!forum/proj-glow
  - icon: slack
    title: slack
    url: https://join.slack.com/t/proj-glow/shared_invite/enQtNzkwNDE4MzMwMTk5LTE2M2JiMjQ1ZDgyYWNkZTFiY2QyYWE0NGI2YWY3ODY3NmEwNmU5OGQzODcxMDBlYzY2YmYzOGM1YTcyYTRhYjA
